---
- name: Restart wyoming satellite
  become: true
  ansible.builtin.systemd_service:
    name: wyoming-satellite
    daemon_reload: true
    state: restarted
    enabled: true
- name: Restart wyoming openwakeword service
  become: true
  ansible.builtin.systemd_service:
    name: wyoming-openwakeword
    daemon_reload: true
    enabled: restarted
    state: started
- name: Restart led service
  become: true
  ansible.builtin.systemd_service:
    name: 2mic_leds
    daemon_reload: true
    enabled: true
    state: restarted
- name: Reboot
  become: true
  reboot:
